services:
  app:
    build: .
    restart: unless-stopped
    container_name: Edura
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SSL: ${DB_SSL}

      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: EduraDB
    ports:
      - "5432:5432"
    volumes:
      - edura_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  edura_data:
